---
- name: Create longhorn-system namespace
  kubernetes.core.k8s:
    name: longhorn-system
    api_version: v1
    kind: Namespace
    state: present

#https://longhorn.io/docs/1.3.2/deploy/install/install-with-helm/
- name: Add Longhorn chart repo
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: "https://charts.longhorn.io"

- name: Deploy latest version of longhorn chart inside longhorn-system namespace
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    release_namespace: longhorn-system
    values: 
      ingress:
        enabled: true
        host: longhorn.{{ k3s_domain }}
        tls: true
        tlsSecret: longhorn.{{ k3s_domain }}
        annotations:
          cert-manager.io/cluster-issuer: "{{ certificate_issuer_name }}"
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/router.middlewares: "traefik-authelia-auth-transform@kubernetescrd,traefik-authelia-auth@kubernetescrd"

- name: Set local-path as not default storageclass
  kubernetes.core.k8s_json_patch:
    name: local-path
    kind: StorageClass
    api_version: storage.k8s.io/v1
    patch:
      - op: add
        path: /metadata/annotations/storageclass.kubernetes.io~1is-default-class
        value: "false"