- name: Create cert-manager namespace
  kubernetes.core.k8s:
    name: cert-manager
    api_version: v1
    kind: Namespace
    state: present

- name: Add jetstack chart repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"

- name: Deploy latest version of cert-manager chart inside cert-manager namespace
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    values:
      installCRDs: true
      extraArgs: 
      - "--dns01-recursive-nameservers-only"
      - "--dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53"

- name: Create CloudFlare API token Secret
  kubernetes.core.k8s:
    state: present
    template:
      path: 'cloudflare-api-token-secret.yaml.j2'

- name: Create CloudFlare Staging Issuer
  kubernetes.core.k8s:
    state: present
    template:
      path: 'cloudflare-staging-issuer.yaml.j2'

- name: Create CloudFlare Issuer
  kubernetes.core.k8s:
    state: present
    template:
      path: 'cloudflare-issuer.yaml.j2'

- name: Read Server CA Certificate
  slurp:
    path: "/var/lib/rancher/k3s/server/tls/server-ca.crt"
  register: server_ca_crt_file

- name: Read Server CA key
  slurp:
    path: "/var/lib/rancher/k3s/server/tls/server-ca.key"
  register: server_ca_key_file

- name: Create Certificate Secret
  kubernetes.core.k8s:
    state: present
    template:
      path: 'server-ca.yaml.j2'

- name: Create Internal Issuer
  kubernetes.core.k8s:
    state: present
    template:
      path: 'internal-issuer.yaml.j2'