# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
---
dashboard:
  enabled: true
  domain: traefik.k3s.stiil.dk
rbac:
  enabled: true
ports:
  web:
    redirectTo: websecure
experimental:
  plugins:
    enabled: true
  kubernetesGateway:
    enabled: true
    certificate:
      group: ""
      kind: "Secret"
      name: "traefik-default-certificate"
additionalArguments:
- "--experimental.plugins.htransformation.modulename=github.com/tomMoulard/htransformation"
- "--experimental.plugins.htransformation.version=v0.2.5"
- "--entryPoints.web.forwardedHeaders.trustedIPs=127.0.0.1/32,192.168.1.5"
- "--entryPoints.websecure.forwardedHeaders.trustedIPs=127.0.0.1/32,192.168.1.5"
- "--providers.file.directory=/etc/conf.d"