---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
  - role: longhorn-prep
  
- hosts: master
  gather_facts: yes
  become: yes
  roles:
  - role: kubernetes-tools
  - role: ansible-role-helm
  - role: nfs-csi
#  - role: sealed-secrets
  - role: cert-manager
  - role: traefik
  - role: cattle-system
  - role: longhorn
