apiVersion: v1
kind: Service
metadata:
  name: {{ include "base_chart.fullname" . }}
  labels:
    {{- include "base_chart.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.service.type }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.service.port }}
      protocol: {{ .Values.service.protocol | default "TCP" }}
      name: {{ .Values.service.name }}
  selector:
    {{- include "base_chart.selectorLabels" . | nindent 4 }}
