- name: Create cattle-system namespace
  kubernetes.core.k8s:
    name: cattle-system
    api_version: v1
    kind: Namespace
    state: present
    
- name: Create cattle-system namespace
  kubernetes.core.k8s:
    name: cattle-global-data
    api_version: v1
    kind: Namespace
    state: present

- name: Add Rancher chart repo
  kubernetes.core.helm_repository:
    name: rancher-latest
    repo_url: "https://releases.rancher.com/server-charts/latest"

- name: Deploy latest version of rancher chart inside cattle-system namespace
  kubernetes.core.helm:
    name: rancher
    chart_ref: rancher-latest/rancher
    release_namespace: cattle-system
    values: "{{ lookup('template', 'values.yaml') | from_yaml }}"

- name: "wait for Rancher to come online"
  ansible.builtin.uri:
    url: "https://{{ rancher_hostname }}/ping"
    status_code: 200
    validate_certs: false
  register: result
  until: result.status == 200
  retries: 60
  delay: 5

- name: Create temporary Rancher access token
  ansible.builtin.uri:
    url: "https://{{ rancher_hostname }}/v3-public/localProviders/local?action=login"
    validate_certs: false
    method: POST
    body_format: json
    body:
      username: admin
      password: "{{ base_password }}"
      ttl: 600000 # 10 min token
      description: "initial setup"
      responseType: json
    status_code: 201
  register: login_response

- name: Set Rancher server-url
  ansible.builtin.uri:
    url: "https://{{ rancher_hostname }}/v3/settings/server-url"
    validate_certs: false
    method: PUT
    headers:
      Authorization: "Bearer {{ login_response.json.token }}"
    body_format: json
    body:
      name: server-url
      value: "https://{{ rancher_hostname }}"

- name: Set Rancher telemetry opt-out
  ansible.builtin.uri:
    url: "https://{{ rancher_hostname }}/v3/settings/telemetry-opt"
    validate_certs: false
    method: PUT
    headers:
      Authorization: "Bearer {{ login_response.json.token }}"
    body_format: json
    body:
      name: telemetry-opt
      value: out

- name: Set Rancher eula-agreed
  ansible.builtin.uri:
    url: "https://{{ rancher_hostname }}/v3/setting"
    validate_certs: false
    method: POST
    headers:
      Authorization: "Bearer {{ login_response.json.token }}"
    body_format: json
    body:
      name: eula-agreed
      value: "{{ ansible_date_time.iso8601 }}"
    status_code: [201, 409]